# Generated by Django 3.0.4 on 2020-04-09 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='calibration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('param_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
                ('value', models.FloatField()),
                ('ts', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='configuration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('param_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
                ('value', models.FloatField()),
                ('ts', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='diagnostics',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('param_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
                ('value', models.FloatField()),
                ('ts', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='pressure',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sensor_name', models.CharField(max_length=50)),
                ('value', models.FloatField()),
                ('ts', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='repiration_rate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.FloatField()),
                ('ts', models.DateTimeField(null=True)),
            ],
        ),
    ]
