# Generated by Django 3.0.4 on 2020-04-09 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RENCI_Ventilator', '0002_auto_20200409_1516'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='diagnostics',
            new_name='Diagnostic',
        ),
        migrations.RenameModel(
            old_name='respiration_rate',
            new_name='Respiration',
        ),
    ]
