# Generated by Django 3.0.4 on 2020-04-09 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RENCI_Ventilator', '0003_auto_20200409_1609'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='configuration',
            new_name='Calibration_1',
        ),
        migrations.RenameModel(
            old_name='calibration',
            new_name='Configuration_1',
        ),
        migrations.RenameModel(
            old_name='Diagnostic',
            new_name='Diagnostic_1',
        ),
        migrations.RenameModel(
            old_name='pressure',
            new_name='Pressure_1',
        ),
        migrations.RenameModel(
            old_name='Respiration',
            new_name='Respiration_1',
        ),
    ]
