# Generated by Django 3.0.4 on 2020-04-09 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RENCI_Ventilator', '0004_auto_20200409_1614'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Calibration_1',
            new_name='Calibration',
        ),
        migrations.RenameModel(
            old_name='Configuration_1',
            new_name='Configuration',
        ),
        migrations.RenameModel(
            old_name='Diagnostic_1',
            new_name='Diagnostic',
        ),
        migrations.RenameModel(
            old_name='Pressure_1',
            new_name='Pressure',
        ),
        migrations.RenameModel(
            old_name='Respiration_1',
            new_name='Respiration',
        ),
    ]
