# Generated by Django 3.0.4 on 2020-04-10 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RENCI_Ventilator', '0005_auto_20200409_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostic',
            name='group',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
