# Generated by Django 3.0.4 on 2020-04-10 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RENCI_Ventilator', '0006_diagnostic_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diagnostic',
            old_name='group',
            new_name='grouping',
        ),
    ]
