# Generated by Django 3.0.4 on 2020-04-10 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RENCI_Ventilator', '0007_auto_20200410_1328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diagnostic',
            old_name='value',
            new_name='result',
        ),
        migrations.RenameField(
            model_name='diagnostic',
            old_name='param_name',
            new_name='test_name',
        ),
    ]
