# Generated by Django 3.0.4 on 2020-04-16 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RENCI_Ventilator', '0008_auto_20200410_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calibration',
            name='value',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='value',
            field=models.CharField(max_length=50),
        ),
    ]
